//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimerCalc.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{""nodes"":[{""Key"":""Timer0"",""Value"":[{""Key"":""Prescaler"",""Value"":[""1:2"",""1:4"",""1:8"",""1:16"",""1:32"",""1:64"",""1:128"",""1:256""]}]},{""Key"":""Timer1"",""Value"":[{""Key"":""Prescaler"",""Value"":[""1:1"",""1:2"",""1:4"",""1:8""]}]},{""Key"":""Timer2"",""Value"":[{""Key"":""Prescaler"",""Value"":[""1:1"",""1:4"",""1:16"",""1:64""]},{""Key"":""Postscaler"",""Value"":[""1:1"",""1:2"",""1:3"",""1:4"",""1:5"",""1:6"",""1:7"",""1:8"",""1:9"",""1:10"",""1:11"",""1:12"",""1:13"",""1:14"",""1:15"",""1:16""]}]}]}")]
        public string timers {
            get {
                return ((string)(this["timers"]));
            }
            set {
                this["timers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{""Timer0"":""// Timer 0\r\nTMR0CS = 0; // internal instruction cycle clock\r\nPSA = 0; // enable prescaler\r\nOPTION_REGbits.PS = $PRESCALER; // $PRESCALER_NAME\r\nTMR0 = $PRELOAD;\r\n\r\n// Interrupts\r\nTMR0IE = 1; // timer 0 overflow interrupt\r\nGIE = 1; // Enables all active interrutps"",""Timer1"":"""",""Timer2"":""// Timer 2\r\nTMR2ON = 1; // enable timer 2\r\nT2CONbits.T2CKPS = $PRESCALER; // prescaler $PRESCALER_NAME\r\nT2CONbits.T2OUTPS = $POSTSCALER; // postscaler $POSTSCALER_NAME\r\nPR2 = $TICKS; // interrupt on value $TICKS\r\n    \r\n// Interrupts\r\nTMR2IE = 1; // timer 0 overflow interrupt\r\nPEIE = 1; // peripheral input enable\r\nGIE = 1; // enables all active interrutps""}")]
        public string timerCodes {
            get {
                return ((string)(this["timerCodes"]));
            }
            set {
                this["timerCodes"] = value;
            }
        }
    }
}
